config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'homepage#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', ad: :unauthenticated_root
    end
  end

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
   # @tasks = Tasks.all
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :fetch_task, only: %i(show edit update destroy)

  def index
    @task = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    @task.valid? ? create_task : handle_task_validation_failed
  end

  def show; end

  private

  def create_task
    @task.save
    current_user.tasks << @task
    flash[:notice] = 'Task created!'
    redirect_to @task
  end

  def handle_task_validation_failed
    flash[:errors] = @task.errors.full_messages
    redirect_back(fallback_location: root_path)
  end

  def task_params
    params.require(:task).permit(:title, :description)
  end

  def fetch_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logout_user_link
    link_to 'Logout', destroy_user_session_path, method: :delete
  end
end

app/views/homepage/index.haml
%p
= link_to 'Logout', destroy_user_session_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todosample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.haml
= form_for @task do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :description
    = f.text_area :description
  %p= f.submit 'Submit'

app/views/tasks/index.haml
%h4 Your tasks

- @task.each do |task|
  %p
    = link_to task.title, task

= button_to "Add task", new_task_path, method: :get if current_user

app/views/tasks/new.haml
%h2 New task

= render 'form'

app/views/tasks/show.haml
%h2= @task.title
%p= @task.description

= button_to "Back", tasks_path, method: :get if current_user